#___APP_NAME_________#
name: app-name

#______INGRESS_VALUES_________#
ingress:
  create: false #if true, create ingres
  host: host.com
  #paths
  paths:
    - path: /path/
      pathType: Prefix

#____DEPLOYMENT_VALUES_____#
deployment:
  replicas: 1
  image: image_name
  tag: tag
  pullPolicy: IfNotPresent
  
  # CONTAINER PORTS
  # ports:
  # - name: http
  #   port: 80
  
  # CONTAINER ENVS
  # envs:
  # - name: NAME1
  #   value: value

  # CONTAINER SECRETS
  # secrets:
  # - name: NAME2
  #   value: base64_value

#____SERVICE_VALUES____#
service:
  create: false #if true, create service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80