#____APP_NAME_______#
name: email-worker

#____DEPLOYMENT_VALUES_____#
deployment:
  replicas: 1
  image: auth-fastapi-2_email-worker
  tag: latest
  pullPolicy: IfNotPresent
  envs:
    - name: WORKER_DEFAULT_QUEUE
      value: auth_emails
  secrets:
    - name: RABBITMQ_URI
      value: YW1xcDovL2V4YW1wbGU6ZXhhbXBsZUBicm9rZXItc2VydmljZS5icm9rZXItbmFtZXNwYWNlLy8=
    - name: SENDER_EMAIL
      value: ZXhhbXBsZQ==
    - name: SENDER_EMAIL_PASSWORD
      value: ZXhhbXBsZQ==