name: auth-server

#______INGRESS_VALUES_________#
ingress:
  create: true
  host: auth-server.com
  paths:
    - path: /auth/
      pathType: Prefix
    - path: /admin/
      pathType: Prefix


#____DEPLOYMENT_VALUES_____#
deployment:
  replicas: 1
  image: auth-fastapi-2_auth-server
  tag: latest
  pullPolicy: IfNotPresent

  ports:
    - name: http
      port: 80
  
  envs:
    - name: DB_TRANSACTIONS_QUEUE
      value: auth_db_transactions
    - name: EMAILS_QUEUE
      value: auth_emails
    - name: ACCESS_TOKEN_EXP
      value: "'10'"
    - name: REFRESH_TOKEN_EXP
      value: "'60'"
    - name: RANDOM_EXP
      value: "'10'"
  secrets:
    - name: RABBITMQ_URI
      value: YW1xcDovL2V4YW1wbGU6ZXhhbXBsZUBicm9rZXItc2VydmljZS5icm9rZXItbmFtZXNwYWNlLy8=
    - name: PRIVATE_KEY
      value: MTc1NTkyNThkM2FjMTQ1ZDcxN2RjYWZlYTMyNzdmZTgyYTNjYjVkNWJhZDAxMjk2OTI1YmRkOWEyZTBjMzM3MA==
    - name: SECRET_KEY
      value: YTg2YTU3ZWQ0MWQ5NzIwYmQ0ODE1OTQ5MTdkYTJiY2E=
    - name: DATABASE_URI
      value: ZXhhbXBsZTpleGFtcGxlQGRhdGFiYXNlLXNlcnZpY2UuZGF0YWJhc2UtbmFtZXNwYWNlL2F1dGg=


#____SERVICE_VALUES____#
service:
  create: true
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80