#___APP_NAME_________#
name: db-worker

#____DEPLOYMENT_VALUES_____#
deployment:
  replicas: 1
  image: auth-fastapi-2_db-worker
  tag: latest
  pullPolicy: IfNotPresent
  secrets:
    - name: ADMIN_USER_EMAIL
      value: YWRtaW5AYWRtaW4uY29t
    - name: RABBITMQ_URI
      value: YW1xcDovL2V4YW1wbGU6ZXhhbXBsZUBicm9rZXItc2VydmljZS5icm9rZXItbmFtZXNwYWNlLy8=
    - name: DATABASE_URI
      value: ZXhhbXBsZTpleGFtcGxlQGRhdGFiYXNlLXNlcnZpY2UuZGF0YWJhc2UtbmFtZXNwYWNlL2F1dGg=
  envs:
    - name: WORKER_DEFAULT_QUEUE
      value: auth_db_transactions