{{- if .Values.configmap.create -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
data:

  {{- range .Values.configmap.keys }}
  {{ .key }}: {{ .value }}
  {{- end }}

{{- end }}