{{- if .Values.secret.create -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
data:

  {{- range .Values.secret.keys }}
  {{ .key }}: {{ .value }}
  {{- end }}

{{- end }}