version: "3"
services:

  #################____DATABASE___#################
  db-server:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    #volumes:
      #- ./data.database:/var/lib/postgresql/data


  #################____BROKER___#################
  broker:
    image: rabbitmq:3.9.13-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - 15672:15672 #Manage
      - 15692:15692 #Metrics


  #################____EMAIL_WORKER___############
  email-worker:
    build:
      context: ../../src/email-worker
      dockerfile: Dockerfile
    environment:
      #____Rabbitmq_Settings____#
      #amqp://<username>:<password>@<hostname>/<vhost_name>
      RABBITMQ_URI: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_SERVER}/${RABBITMQ_VHOST}
      WORKER_DEFAULT_QUEUE: ${EMAILS_QUEUE}

      #____Email_Settings_____#
      SENDER_EMAIL: ${SENDER_EMAIL}
      SENDER_EMAIL_PASSWORD: ${SENDER_EMAIL_PASSWORD}
    volumes:
      - ../../src/email-worker/:/code/


  #################____DB_WORKER___##################
  db-worker:
    build:
      context: ../../src/db-worker
      dockerfile: Dockerfile
    environment:
      #_____Auth_Settings_______#
      ADMIN_USER_EMAIL: ${ADMIN_USER_EMAIL}

      #____Rabbitmq_Settings____#
      #amqp://<username>:<password>@<hostname>/<vhost_name>
      RABBITMQ_URI: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_SERVER}/${RABBITMQ_VHOST}
      WORKER_DEFAULT_QUEUE: ${AUTH_DB_TRANSACTIONS_QUEUE}
      
      #____Database_Settings____#
      #<username>:<password>@<hostname>/<db_name>
      DATABASE_URI: ${DB_USER}:${DB_PASSWORD}@${DB_SERVER}/${DB_NAME}
    volumes:
      - ../../src/db-worker/:/code/
  

  ################__NGINX(API-GATEWAY)__############
  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx.confs/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-server
    ports:
      - 8080:80

  #################____AUTH_API___##################
  auth-server:
    build:
      context: ../../src/auth-server
      dockerfile: Dockerfile
    environment:
      #____Database_Settings____#
      #<username>:<password>@<hostname>/<db_name>
      DATABASE_URI: ${DB_USER}:${DB_PASSWORD}@${DB_SERVER}/${DB_NAME}

      #____Auth_Settings____#
      PRIVATE_KEY: ${PRIVATE_KEY}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXP: ${ACCESS_TOKEN_EXP}
      REFRESH_TOKEN_EXP: ${REFRESH_TOKEN_EXP}
      RANDOM_EXP: ${RANDOM_EXP}

      #____Rabbitmq_Settings____#
      #amqp://<username>:<password>@<hostname>/<vhost_name>
      RABBITMQ_URI: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_SERVER}/${RABBITMQ_VHOST}
      DB_TRANSACTIONS_QUEUE: ${AUTH_DB_TRANSACTIONS_QUEUE}
      EMAILS_QUEUE: ${EMAILS_QUEUE}

      #___TEST_MODE_____#
      TEST_MODE: ${TEST_MODE}
    volumes:
      - ../../src/auth-server/:/code/

  #################____AUTH_API___##################
  test-app:
    build: 
      context: ../../src/test-app
      dockerfile: Dockerfile
    environment:
      AUTHORIZATION_URL: ${AUTHORIZATION_URL}
    volumes:
      - ../../src/test-app/:/code/