# This workflow will test, create docker images and push to dockerhub
name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Build_Base_Docker_Images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        # TO use ${{ env.RELEASE_VERSION }}
  Tests:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
  Create_Docker_Images:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!